//
//  DrawModels.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import PhotosUI
import UIKit

// MARK: - Draw Enum

enum Draw {
    enum Request {}
    enum Response {}
    enum DisplayData {}
}

// MARK: - Draw Request Extension

extension Draw.Request {

    struct DrawingInfo {
        let image: UIImage
    }
}

// MARK: - Draw Response Extension

extension Draw.Response {

    struct SavingError {
        let error: PHPhotosError
    }
}

// MARK: - Draw DisplayData Extension

extension Draw.DisplayData {

    struct SavingResult {
        let title: String
        let message: String
    }
}
