//
//  DrawPresenter.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

// MARK: - DrawPresentationLogic Protocol

protocol DrawPresentationLogic {
    func presentImageSavingSuccessfully()
    func presentImageSavingFailed(response: Draw.Response.SavingError)
}

// MARK: - DrawPresenter

class DrawPresenter {

    // MARK: - Internal Properties

    weak var viewController: DrawDisplayLogic?
}

// MARK: - DrawPresentationLogic Extension

extension DrawPresenter: DrawPresentationLogic {

    func presentImageSavingSuccessfully() {
        let viewModel = Draw.DisplayData.SavingResult(title: "Your drawing has been saved successfully!",
                                                      message: "Open your Photo Library to see the saved picture.")
        viewController?.displaySavingResult(viewModel: viewModel)
    }

    func presentImageSavingFailed(response: Draw.Response.SavingError) {
        let message: String
        switch response.error.code {
        case .accessRestricted, .accessUserDenied:
            message = "Please open Settings and allow access to your Photo Library to save this drawing as an image."
        default:
            message = "Check out the detailed error: \(response.error.localizedDescription)."
        }

        let viewModel = Draw.DisplayData.SavingResult(title: "Your drawing was not saved!",
                                                      message: message)
        viewController?.displaySavingResult(viewModel: viewModel)
    }
}
