//
//  DrawPresenter.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

// MARK: - DrawPresentationLogic Protocol

protocol DrawPresentationLogic {
    func presentImageSavingSuccessfully()
    func presentImageSavingFailed(response: Draw.Response.SavingError)
}

// MARK: - DrawPresenter

class DrawPresenter {

    // MARK: - Internal Properties

    weak var viewController: DrawDisplayLogic?
}

// MARK: - DrawPresentationLogic Extension

extension DrawPresenter: DrawPresentationLogic {

    func presentImageSavingSuccessfully() {
        let viewModel = Draw.DisplayData.SavingResult(title: Const.Draw.successAlertTitle,
                                                      message: Const.Draw.successAlertMessage)
        viewController?.displaySavingResult(viewModel: viewModel)
    }

    func presentImageSavingFailed(response: Draw.Response.SavingError) {
        let message: String
        switch response.error.code {
        case .accessRestricted, .accessUserDenied:
            message = Const.Draw.failedAlertAcessDeniedMessage
        default:
            message = Const.Draw.failedAlertDefaultMessage(errorDescription: response.error.localizedDescription)
        }

        let viewModel = Draw.DisplayData.SavingResult(title: Const.Draw.failedAlertTitle,
                                                      message: message)
        viewController?.displaySavingResult(viewModel: viewModel)
    }
}
