//
//  DrawRouter.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

// MARK: - DrawRoutingLogic Protocol

protocol DrawRoutingLogic {}

// MARK: - DrawDataPassing Protocol

protocol DrawDataPassing {
    var dataStore: DrawDataStore? { get }
}

// MARK: - DrawRouter

class DrawRouter: DrawDataPassing {

    // MARK: - Internal Properties

    weak var viewController: DrawViewController?
    var dataStore: DrawDataStore?
}

// MARK: - DrawRoutingLogic Extension

extension DrawRouter: DrawRoutingLogic {}
