//
//  DrawInteractor.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

// MARK: - DrawBusinessLogic Protocol

protocol DrawBusinessLogic {}

// MARK: - DrawDataStore Protocol

protocol DrawDataStore {}

// MARK: - DrawInteractor

class DrawInteractor: DrawDataStore {

    // MARK: - Internal Properties

    var presenter: DrawPresentationLogic?
    var worker: DrawWorker?
}

// MARK: - DrawBusinessLogic Extension

extension DrawInteractor: DrawBusinessLogic {}
