//
//  DrawPresenter.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

// MARK: - DrawPresentationLogic Protocol

protocol DrawPresentationLogic {}

// MARK: - DrawPresenter

class DrawPresenter {

    // MARK: - Internal Properties

    weak var viewController: DrawDisplayLogic?
}

// MARK: - DrawPresentationLogic Extension

extension DrawPresenter: DrawPresentationLogic {}
