//
//  DrawInteractor.swift
//  PencilDrawingDemo
//
//  Created by Konstantin Stolyarenko on 11.09.2023.
//  Copyright © 2023 SKS. All rights reserved.
//
//  This file was generated by the SKS Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import PhotosUI
import UIKit

// MARK: - DrawBusinessLogic Protocol

protocol DrawBusinessLogic {
    func saveDrawing(request: Draw.Request.DrawingInfo)
}

// MARK: - DrawDataStore Protocol

protocol DrawDataStore {}

// MARK: - DrawInteractor

class DrawInteractor: DrawDataStore {

    // MARK: - Internal Properties

    var presenter: DrawPresentationLogic?
    var worker: DrawWorker?
}

// MARK: - DrawBusinessLogic Extension

extension DrawInteractor: DrawBusinessLogic {

    func saveDrawing(request: Draw.Request.DrawingInfo) {
        PHPhotoLibrary.shared().performChanges({
            PHAssetChangeRequest.creationRequestForAsset(from: request.image)
        }, completionHandler: { [weak self] _, error in
            DispatchQueue.main.async {
                guard let self = self else { return }
                if let error = error as? PHPhotosError {
                    let response = Draw.Response.SavingError(error: error)
                    self.presenter?.presentImageSavingFailed(response: response)
                    return
                }
                self.presenter?.presentImageSavingSuccessfully()
            }
        })
    }
}
